runtime: python310
instance_class: F4_1G
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

handlers:
  - url: /static
    static_dir: static/static
  - url: /.*
    script: auto

readiness_check:
  path: "/"
  check_interval_sec: 10
  timeout_sec: 10
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 1
